print("Welcome To The Interactive Personal Data Collecter!",end="\n\n")
name=input("Please Enter Your Name:")
age=int(input("Please Enter Your Age:"))
height=float(input("Please Enter Your Height In Meters:"))
num=int(input("Please Enter Your Favourite Number:"))
print("\n")
print("Thank You! Here Is The information We Have Collected",end="\n\n")
print("Name:",name,"(Type:",type(name),", " "Memory Address:",id(name),")")
print("Age:",age,"(Type:",type(age),", " "Memory Address:",id(name),")")
print("Height:",height,"(Type:",type(height),", " "Memory Address:",id(height),")")
print("Favourite Number:",num,"(Type:",type(num),", " "Memory Address:",id(num),")",end="\n\n")
print("Your Birth Year Is Approximately:",2026-age,end="\n\n")
print("Thank You For Using The Personal Data Collector. Goodbye!")